### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Jennica416** [nicolehawe/STAT545-HW-Hawe-Nicole#2]
Hi @nicolehawe,

Peer Review: 0 (Satisfactory)

Nice to "meet" you.  For a "newbie", I thought your assignment showed some great learning with the headers and being able to embed a link as well as create a bulleted list. 

As the assignment was partly about getting to know each other, it would have been appreciated if you included more information about yourself academically and/or personally.  There was also supposed to be a bit of a reflection on your learning from this assignment and this was not included.  For the future, it might also be good to learn how to create a Table of Contents to help navigate the report. 

Congrats on getting the first assignment completed :) 

- Jennica

**Comment by nicolehawe** [comment]
Hi @Jennica416 , thanks for the feedback. Unfortunately I think you were only supposed to add me as a collaborator to your repo. I am supposed to review your homework, however you are supposed to review homework for someone else.

**Comment by Jennica416** [comment]
You are completely right... thanks for flagging this so I was able to complete the other peer review on time. Much appreciated!
